---
title: "Effects of bariatric surger and weight loss on resting-state functional connectivity"
author:
- xxx [1]
- xxx [1][2]
- xxx [1][2][3]
- xxx [1][2]
date: 1 Max-Planck-Institute for Human Cognitive and Brain Sciences, Leipzig \newline
  2 CRC 1052 "Obesity Mechanisms", Subproject A1, University of Leipzig \newline 3
  Day Clinic for Cognitive Neurology, University Clinic Leipzig
output: word_document
editor_options:
  chunk_output_type: console
bibliography: bibliography.bib
---

```{r "environment setup", include=FALSE}

# load packages
library(car) # version 3.0.9
library(plyr) # version 1.8.6
library(dplyr) # version 1.0.2
library(tidyr) # version 1.1.2
library(kableExtra) # version 1.2.1
library(ggplot2) # version 3.3.2
library(patchwork) # version 1.0.1; API for sequentially building up a plot (similar to gridExtra and cowplot)
#library(cowplot)
library(RColorBrewer) # version 1.1.2
library(psych) # version 2.0.8
#library(lsr) 
#library(wesanderson) # colour palette
#library(haven)


library(knitr) # version 1.30
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE) # fig.height=2, fig.width=4)
options(knitr.table.format = "latex") 
# put the path to this file here (working directory for Rmarkdown):
opts_knit$set(root.dir = getwd())

```
# Abstract

\newpage
# Introduction

<!-- obesity and interventions -->
Over the past decades, the global burden of obesity has increasingly been confronted as a matter of urgency by research.
Besides metabolic dysfunctions, obesity has been consistently associated with reduced gray matter volume, less intact white matter structure and reduced cognitive function [@Beyer_2019; @Zhang_2018]. 
Luckily, dietary interventions such as caloric restriction and related metabolic improvements, and weight loss have been suggested to improve neuronal plasticity and cognitive performance [@Witte_2009; @Zhang_2018; @Veronese_2017].
In some cases behavioral intervention fail to yield the desired success regarding weight loss. There are non-behavioral alternatives at hand.
<!-- bars most invasive (brain metabolism), last resort -->
Bariatric surgery is one promising option to combat morbid obesity, as it rapidly improves weight status, metabolic dysfunctions, and co-morbidities, such as diabetes [@]. Roux-en-Y gastric bypass (RYGB) is the most common procedure as it not only restricts the food intake by reducing stomach volume but also affects the absorption of macronutrients and the hormonal profile [@]. <!-- ref for "common", ref for procedure -->
Other widely used procedures are vertical sleeve gastrectomy (VSG) and gastric banding (GB) which only restrict food consumption. <!-- mehr zu Veränderung in Gasto-intestinaler Physiologie -->
<!-- Neural mechanisms/concurrent plasticity? -->
Precise mechanisms as to how bariatric surgery leads to recovery are yet to be elucidated. As a first step, a comprehensive understanding of the concurrent physiological changes underlying weight loss and recovery is needed. This will inform inferences about potential mechanisms and either support interventions proven to be effective or ideally allow imitating them with less invasive alternatives.

<!-- severe nutritional stress [@Crujeiras_2017] -->

<!-- Reward network -->
Little is known about the potential beneficial effects of bariatric surgery on brain function in the obese population. Thus, one recently emerging research focus is how brain metabolism and functional connectivity changes in response to surgery, in particular with regard to hedonic motivations for food, which play a fundamental role in weight relapse.
The reward network comprising the ventromedial prefrontal cortex (vmPFC), the striatum (STR) but also the anterior insula (antIns) has been linked to food valuation processes in decision-making in lean individuals [@Bartra_2013; @Hare_2011; @Hutcherson_2012; @Schmidt_2018; @Wiemerslage_2016]. These regions also seem to be altered after bariatric surgery [@Lips_2014; @Hogenkamp_2016; @Garcia_2012]. <!-- Zitationen checken -->
<!-- Normalization of connectivity --> Obese individuals exhibited increased connectivity between frontal and mesolimbic regions and weaker connectivity within regions of the mesolimbic system (encompassing limbic and striatal regions). But these differences seemed to normalize, as trends reversed when looking at the resting state connectivity after compared to before the surgery [@Duan_2020]. Resting state activitiy increased in subcortical regions, such as the insula and striatum<!-- specifically putamen --> [@Wiemerslage_2016]. 
<!-- mechanism reward and appetite, overeating --> Interestingly, patients report changes in food preferences and eating behavior after the surgery that may influence weight loss beyond malabsorption of nutrients and restricted food ingestion. Those psychophysiological and behavioral effects are presumably related to post-surgical changes in visceral sensory perceptions and endocrinological signaling. Corresponding information is processed by the fronto-mesolimbic system and affects appetite and reward signalling which may influence weight regulation [@Mulla_2017; @Nudel_2019].
<!-- results in lean -->

<!-- results in obese longitudinal -->
<!-- Similarly, several studies have found differences in resting-state activity in reward regions depending on weight status.  -->

<!-- On the other hand, BMI prior to the surgery was associated with changes in connectivity [@Duan_2020]. -->

<!-- s concerning such processes following a surgical intervention are inconclusive. -->

<!-- important differences in the response to visual food-related cues between thin and reduced-obese individuals that place the latter group at an increased risk of  -->

<!-- Though there exists strong evidence for important differences in the .. between lean or normal-weight individuals and obese individuals, few studies have investigated the ... and even fewer compared reduced-obese individuals reduced-obese individuals -->
<!-- [@Garcia_Garcia_2012] -->


<!-- Default mode network --> 
Because multiple resting state networks are relevant to obesity and associated with abnormal neurocircuitry interactions [@Ding_2020], extensive research has been devoted to investigating the the relationship between the control network and the reward network. However, the dynamics within the default network may also be of importance because it is associated with processing of self-referent as well as introspective information, such as hunger sensation [@;@] and appetite [@Tregellas_2011]. <!-- parietal activation correlated with appetite measures after an overnight fast [@Tregellas_2011]. --> 
Weight regulation and energy expenditure, on the other hand, are highly dependent on a complex interplay of external and internal sensory processing, as well as molecular homeostasis regulation. 
<!-- Obesity = decompensation of the psychophysiological system that ensures homeostasis. -->

The default mdoe network is mainly composed of the posterior cingulate cortex (PCC)/precuneus, the medial prefrontal cortex (MPFC) and inferior and lateral parietal cortex (IPC, LPC; approx. BA 39) [@Raichle_2015]. The right ventral anterior cingulate cortex (VACC), superior frontal cortex (SFC), and inferior temporal cortex (ITC) show weaker but also reliable association with the PCC over the course of one year. Even broader conceptions count left VACC, middle temporal gyrus (MTG), and parahippocampal cortex, although associations with the PCC are not as stable [@Chou_2012].
<!-- study results --> 
Functional connectivity of this network has been shown to be linked to BMI [@Beyer_2017] and altered after bariatric surgery [@Olivo_2017].
Generally, studies show an increased activation in the default mode network, especially in the precuneus and posterior cingulate cortex (PCC) in obese individuals [@Kullmann_2011; @].
Comparing spontaneous activitiy before and after surgery shows a decrease in areas including superior frontal regions<!-- gehört zu SFC -->, and a decrease superior parietal lobule when in sated state [@Wiemerslage_2016].
Concerning spontaneuous functional connectivity in these regions, patient having undergone bariatric surgery resemble normal-weight individuals rather than obese individual in having a weaker connectivity within the default mode network [@Frank_2013].
A longitudinal study investigating confirmed that while there was stronger connectivity in the default model network <!-- (PCC with anterior STG and anterior temporal fusiform gyrus and the Precuneus with the anterior STG) --> in obese patients before the surgery, it seemed weakened over the course of one year. Because differences between lean controls and obese individuals that existed prebariatric surgery were no longer detectable after the surgery, the authors argue for a normalization in functional connectivity<!-- and PCC/PC connectivity with anterior STG are most affected by the surgery -->[@Olivo_2017].
Consistent with these findings, other studies reported a reduction of functional connectivity of these and other regions of the default mode network, such as the VMPFC <!-- with the dorsolateral prefrontal cortex (DLPFC) --> after the surgery [@Li_2018].

<!-- The exact mechanisms of how bariatric surgery affects functional plasticity needs to be investigated and especially the role of weight and weight change. -->
... 
It has been stated that among patients undergoing surgery, change in BMI was<!-- negatively --> correlated with the changes in connectivity of the default mode network, namely between the PCC/precuneus and the DLPFC [@Li_2018].
On the other hand, there are also indicators of reduced functional integrity, e.g. for the anterior cingulate cortex (ACC) at resting state compared to lean individuals [@Kullmann_2011]. ...

<!-- On the other hand, connectivity also served as a predictor of weight loss after surgery. -->

<!--  -->


<!-- novelty statement --> As described previously, several studies have investigated the effects of bariatric surgery on the intrinsic functional connectivity in patients. Yet, to our knowledge there is no quasi-experimental study, comparing a cohort of patients to a cohort with similar characteristics but unexposed to the intervention, i.e. bariatric surgery, over an extended time period as would be demanded to draw more substantiated inference [@George_2016].
<!-- hypotheses --> In this study, we aim to bridge this gap and investigate possible dynamics of within-reward network connectivity before and after bariatric surgery by comparison with a contemporaneously measured waiting-control group. Moreover, we will explore whether the changes in functional connectivity are associated with the amount of weight lost after bariatric surgery treatment in obesity to explore a potential gradient link. In addition, we will investigate potential changes in within-network functional connectivity after surgery in other resting-state networks such as default mode network (DMN).
Participants are measured at baseline, at 6 months and at 24 months to capture both phases of rapid weight-loss and maintenance as expected from non-surgical interventions [@Shai_2008]. Notably, we will consider that different courses in increase and decrease of functional connectivity that are not necessarily linear are possible over the course of one year, depending on the phase of weight management [@Olivo_2017].

<!-- group effect because direct effect of intervention surgery -> rsfmri (cares lessfreq, less preoccupation with hunger, less/more reward sensitivity) vs. sugery -> BMI -> rsfmri (neural signalling, fatty tissue) -->

\newpage
# References